language: cpp

cache:
  ccache: true
  timeout: 1000

env:
  global:
    - QTVER=5.12.1
    - PPAQTVER=512
    - QTIFWVER=3.0.6
    - APPIMAGEVER=11
    - ARCH_ROOT_DATE=2019.02.01
    - ARCH_ROOT_URL=https://mirror.rackspace.com/archlinux
    - FFMPEG_VERSION=4.1.1
    - RELEASE_BUILD=1

os: osx
osx_image: xcode8
compiler: clang

before_install: |
  if [ -z "${ANDROID_BUILD}" ]; then
    if [ "${TRAVIS_OS_NAME}" = linux ] && [ -z "${ARCH_ROOT_BUILD}" ]; then
      docker pull ${DOCKERIMG}
      docker ps -a
      docker run -it -d -v ${PWD}:/sources -v $HOME/.ccache:/ccache -e CCACHE_DIR=/ccache -w /sources --name ${DOCKERSYS} ${DOCKERIMG} /bin/sh
    elif [ "${TRAVIS_OS_NAME}" = osx ]; then
      brew unlink python
      brew update
      brew upgrade
      brew link --overwrite numpy
    fi
  fi

install:
  - chmod +x ports/ci/travis/install_deps.sh
  - ports/ci/travis/install_deps.sh

before_script: |
  if [ "${ANDROID_BUILD}" = 1 ]; then
    export COMPILESPEC=android-${COMPILER}
  elif [ "${ARCH_ROOT_BUILD}" = 1 ] && [ ! -z "${ARCH_ROOT_MINGW}" ]; then
    export CXX=${ARCH_ROOT_MINGW}-w64-mingw32-g++
    export COMPILESPEC=win32-g++
  elif [ "${TRAVIS_OS_NAME}" = linux ]; then
    if [ "${CXX}" = g++ ]; then
      export COMPILESPEC=linux-g++
    elif [ "${CXX}" = clang++ ]; then
      export COMPILESPEC=linux-clang
    fi
  elif [ "${TRAVIS_OS_NAME}" = osx ]; then
    brew link --force qt5
    if [ "${CXX}" = g++ ]; then
      export COMPILESPEC=macx-g++
    elif [ "${CXX}" = clang++ ]; then
      export COMPILESPEC=macx-clang
    fi
  fi

script:
  - chmod +x ports/ci/travis/build.sh
  - ports/ci/travis/build.sh

after_success:
  - chmod +x ports/ci/travis/deploy.sh
  - ports/ci/travis/deploy.sh

branches:
  only:
    - master

notifications:
  recipients:
    - hipersayan.x@gmail.com
  email:
    on_success: change
    on_failure: change

deploy:
  - provider: bintray
    user: hipersayanx
    key:
      secure: nk14s1Ud2d4mSrUE2GE8LoWBQxGPiQgwnarx4rVAslOcUHRet+Tj9rSeQfW85oUWGT9LSGvob9il+cvbukoZDBbCyw1VyiO4n4XqaUvmz9/Oh9+7It51eYan/sUxxsiANB3D6c0sklpwg3KeZqYWqS/DoYsOIXA4YBelvFGezm+JZoueJokA7MpZv6rjltVD7WkIA3etoOleofXhcHFr5FAYzPtFN0BGgVmuIIunuOxVCkz1nkR/ucaIrcckpt7XU/WHJ4nrKNb8eUWSxVdklbK7F3MBebe+1ZmK5Gd1Vum378PqT6CjHKsLe1LGhEA5exHWtFlI3YR/u+DqJ9WJic1ykQV6d4BNoBGbWicNcVJuljQRTN+aGGPNMGN5mw7FYdasYKz94Lu7IZsDytAPxkitjbiOF9rZIBkGkHybZdcqCc/nkoXVKhfWaTkoKtQ4UHo32lE6fkIL5QMWwnfMY1IyQvcxkhoevzU0woZt2jvxb5/nHr+fHhekzdWqaWDhdLeViF1G0zZMuG7o6rquLIgzbmYieq1XO0Hoj6lSglGDpCXk2iVbkZetO252Bgzf/wype93HABGmSb48DXyp1tRTgBzh12IbTazrtS2fNMmMpCqNOIy4OvkIwWEKXQKrc53Zowcf3sG2OuGDVwCdGil82PtE+LQN9AiA8gBdU8E=
    on:
      branch: master
      condition: $DAILY_BUILD = 1
    skip_cleanup: true
    file: "$TRAVIS_BUILD_DIR/.bintray.js"
  - provider: releases
    api_key:
      secure: ZmstNQAkYnWdGab437ocr2P613/xqpDLMS2IKOT/n+r3fVCNqhHj7itTTpzSqVQ1LxFRbc5uw22F8Ha6H6kmbtFLs6GETXiTzaqfT6rdwfzzQJa6zZlEF/hWy5fFJzWOQs/e3nYdk2G/eDCWXw3rep4jpzHoxvEYDVlyIUAIkCTloKCYhecUvS/heV88llfZXtqIkYjjNTjQphfgbY67607XcHd0n3ZMxzohGq5DHM4N7KPzo9I/IAzaFz1U5/9hx/r3cogcZmBEpLnXGlRw3pgszdCULlDJVCwqS2b4bYkdWVMWU2T7hDk2K9LUXGjauCbuvMaebNNcitr8K9LHJ8F4OnOKZx3J95NSCMFZhfhlXEW+SLCLzNgKJZ4uldT1xoKTgB0ZdeoCW00yZUT/YWmjin6GaUjkaMXqe2gOGl8S9KcuF/M9VIC4XQawvrYKtgyX5/7jkdKlUTts92hMU6AQ3MT/1oGWsHNrwe9qExYiOUaJss3AiCp6izRFDrSOiG03d8enMDYOZiDZghk8NQ2udRGwFq0c8suPQ+hRB9yNnrnHqlTPAXhKQXHNv78KMo2mGLMiVstx4YTsN3BmZUksfiouB48U3/wy6/cmIw5+Bp/YtAYL2JV2uujG87kUP66Zl/3j6Fs2a6EERWd8WTVYdGZC0TbY4yfPhbpEBUQ=
    file_glob: true
    file:
      - $TRAVIS_BUILD_DIR/ports/deploy/packages_auto/*/*
    skip_cleanup: true
    overwrite: true
    draft: true
    on:
      tags: true
      branch: master
      condition: $RELEASE_BUILD = 1
      repo: webcamoid/webcamoid
